# Generated by Django 2.0 on 2020-06-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200603_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20, verbose_name='艺名')),
                ('addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('mail', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('qqnum', models.IntegerField(verbose_name='QQ号')),
            ],
            options={
                'verbose_name': '站长信息',
                'verbose_name_plural': '站长信息',
            },
        ),
    ]
