# Generated by Django 2.0 on 2020-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='sign',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='about',
            name='qqnum',
            field=models.CharField(max_length=11, verbose_name='QQ号'),
        ),
    ]
