# Generated by Django 2.0 on 2020-06-04 05:42

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200604_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容'),
        ),
    ]
