# Generated by Django 2.0 on 2020-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200615_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, default='/static/image/inroad.jpg', null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片'),
        ),
    ]
